name: Playwright Python Tests

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install Playwright Browsers
              run: |
                  python -m playwright install --with-deps

            - name: Run Pytest
              env:
                  CI: true
              run: |
                  pytest --html=report.html --self-contained-html

            - name: Upload Test Report (artifact)
              uses: actions/upload-artifact@v4
              with:
                  name: pytest-report
                  path: report.html
